### ISSUE TITLE
Why can't AppImageUpdate update itself when prompted by the user?

### ISSUE THREAD

**Issue by RagglenLove** [AppImageCommunity/AppImageUpdate#221] opened 2023-04-25 10:20 UTC
As you can see from the screenshot, AppImageUpdate isn't signed and so cannot be updated.

![Screenshot_2023-04-25_18-05-56](https://user-images.githubusercontent.com/45503845/234247510-689ac326-f3dc-463f-b893-3d075bae8af6.png)

Why is this?

For being able to update the updater is a good idea for security reasons, users should be able to update it when updates are available.

**Comment by TheAssassin** [comment] 2023-04-25 10:38
It did get updated. It just warns about the missing signature, that's all. The update was successful.

This should be communicated more clearly, I guess.

**Comment by RagglenLove** [comment] 2023-04-25 11:13
Thanks for the clarification!

**Comment by TheAssassin** [comment] 2023-04-25 13:03
Let's keep this open as a reminder.

**Comment by RagglenLove** [comment] 2023-04-27 09:29
> This should be communicated more clearly, I guess.

It would be nice if this is how it looked to avoid confusion:

![Screenshot_2023-04-27_17-05-19](https://user-images.githubusercontent.com/45503845/234820952-00be087a-f6bc-47f8-86ba-76dd69336e3c.jpg)

**Comment by axelsimon** [comment] 2023-08-24 10:11
Using the word "problem" will inherently make users think that whatever action they were trying to do failed.

A yellow line also indicates the thing failed.

Someone with UI/UX/design experience needs to look at this to better convey the right information, because right now the application tells you the update failed.

**Comment by Drugoy** [comment] 2023-09-08 23:36
> Let's keep this open as a reminder.

@TheAssassin In the current state the ticket is basically about changing the GUI to better convey to the user that the updated succeeded, it's just that the new file was not signed and thus is a dupe of #173

**Comment by TheAssassin** [comment] 2023-09-09 11:38
True. Let's close this issue then.

**Closed by TheAssassin** 2023-09-09 11:38 UTC
